before_script:
  - docker info

stages:
  - build
  - test
  - deploy

standalone_build:
  stage: build
  script:
    - docker-compose build

standalone_test:
  stage: test
  script:
    - docker-compose run standalone yarn test

prod_deploy:
  stage: deploy
  script:
    - docker build -t deployer -f ./Dockerfile-deploy .
    - docker run -e VAGRANT_LINODE_KEY deployer bash -c 'cd /vagrant && vagrant up --provision --provider=linode'
