image: docker:git

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CONTAINER_REGISTRY: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2
  # See https://about.gitlab.com/2019/07/31/docker-in-docker-with-docker-19-dot-03/
  DOCKER_TLS_CERTDIR: ''

services:
  - docker:dind

#before_script:
#  - docker info
# - ls rts-assets/
# - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CONTAINER_REGISTRY}
# TODO pull docker image for caching and use cache-from

stages:
  - build
  - test
  - deploy

standalone_build:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - rts-assets/
      - ShaderParticleEngine
      #- node_modules/
  tags:
    - docker
  stage: build
  script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CONTAINER_REGISTRY}
    - docker pull ${CONTAINER_REGISTRY}/sr_main:latest || true
    - docker pull ${CONTAINER_REGISTRY}/sr_main:builder || true
    - docker build --target builder --cache-from ${CONTAINER_REGISTRY}/sr_main:builder -t ${CONTAINER_REGISTRY}/sr_main:builder .
    - docker build --cache-from ${CONTAINER_REGISTRY}/sr_main:builder --cache-from ${CONTAINER_REGISTRY}/sr_main:latest -t ${CONTAINER_REGISTRY}/sr_main:latest .
    - docker tag ${CONTAINER_REGISTRY}/sr_main:latest ${CONTAINER_REGISTRY}/sr_main:$CI_COMMIT_SHA
    - docker push ${CONTAINER_REGISTRY}/sr_main:$CI_COMMIT_SHA
    - docker push ${CONTAINER_REGISTRY}/sr_main:latest
    - docker push ${CONTAINER_REGISTRY}/sr_main:builder

standalone_test:
  tags:
    - docker
  stage: test
  image: ${CONTAINER_REGISTRY}/sr_main:builder
  script:
    - yarn install --build-from-source --frozen-lockfile
    - yarn test

## not working for now
# standalone_coverage:
#   tags:
#     - docker
#   image: ${CONTAINER_REGISTRY}/sr_main:builder
#   stage: test
#   only:
#     - master
#   script:
#     - yarn install --build-from-source --frozen-lockfile
#     - yarn coverage

prod_deploy:
  tags:
    - docker
  image:
    name: hashicorp/terraform:0.12.29
    entrypoint: ['']
  stage: deploy
  only:
    - master
  script:
    - terraform init
    - export TF_VAR_sr_main_sha=${CI_COMMIT_SHA}
    - terraform apply -auto-approve
