image: docker/compose:1.24.0-rc1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - rts-assets/
    - ShaderParticleEngine
#  - node_modules/

before_script:
  - docker info
  - apk add --no-cache git openssh-client
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - ls rts-assets/
#   - docker run -v `pwd`:/sr node:alpine sh -c 'cd /sr && yarn; chown -R 1001:1001 ./*'

stages:
  - build
  - test
  # - deploy

standalone_build:
  stage: build
  script:
    - docker-compose build

standalone_test:
  stage: test
  script:
    - docker-compose run standalone yarn test

# prod_deploy:
#   stage: deploy
#   script:
#     - docker build -t deployer -f ./Dockerfile-deploy .
#     - docker run -e VAGRANT_LINODE_KEY -e ANSIBLE_ID_RSA -e ANSIBLE_ID_RSA_PUB deployer bash -c 'mkdir -p /vagrant/.vagrant/machines/sr/linode; echo "12037264" > /vagrant/.vagrant/machines/sr/linode/id; echo "$ANSIBLE_ID_RSA" > /vagrant/id_rsa; echo "$ANSIBLE_ID_RSA_PUB" > /vagrant/id_rsa.pub; cd /vagrant && vagrant up --provider=linode && vagrant provision'
