before_script:
  - docker info

stages:
  - build
  - test
  - deploy

standalone_build:
  stage: build
  script:
    - docker-compose build

standalone_test:
  stage: test
  script:
    - docker-compose run standalone yarn test

prod_deploy:
  stage: deploy
  script:
    - docker build -t deployer -f ./Dockerfile-deploy .
    - docker run -e VAGRANT_LINODE_KEY -e ANSIBLE_ID_RSA -e ANSIBLE_ID_RSA_PUB deployer bash -c 'mkdir -p /vagrant/.vagrant/machines/sr/linode; echo "12037264" > /vagrant/.vagrant/machines/sr/linode/id; echo $ANSIBLE_ID_RSA > /vagrant/id_rsa; echo $ANSIBLE_ID_RSA_PUB > /vagrant/id_rsa.pub; cd /vagrant && vagrant up --provider=linode && vagrant provision'
