version: '3'
services:
  standalone:
    image: registry.gitlab.com/monofuel34089/system-redemption/sr_main:latest
    build:
      # NB. this does not actually work
      # https://github.com/docker/compose/issues/883
      #cache_from:
      #  -  registry.gitlab.com/sr_main:builder
      #  -  registry.gitlab.com/sr_main:latest
      context: .
    restart: always
    ports:
      - '3000:3000'
    environment:
      IP_ADDRESS: 0.0.0.0
  dev:
    build:
      context: .
      target: builder
    restart: always
    # NB. run `yarn watch` locally to update code
    command: ash -c 'yarn install --build-from-source --frozen-lockfile && yarn server:watch'
    volumes:
      - ./:/sr
      - /sr/node_modules
    ports:
      - '3000:3000'
      # TODO debugger
    environment:
      IP_ADDRESS: 0.0.0.0
  deploy:
    image: hashicorp/terraform:0.13.5
    entrypoint: /bin/ash
    volumes:
      - ./:/sr
    environment:
      - TF_VAR_linode_token
      - LINODE_TOKEN
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
