version: '3.2'
services:
  standalone:
    image: registry.gitlab.com/sr_main:latest
    build:
      # NB. this does not actually work
      # https://github.com/docker/compose/issues/883
      cache_from:
        -  registry.gitlab.com/sr_main:builder
        -  registry.gitlab.com/sr_main:latest
      context: .
    restart: always
    ports:
      - '3000:3000'
    environment:
      SR_INTERFACE: 0.0.0.0
