version: '3.2'
services:
  standalone:
    image: ${CONTAINER_REGISTRY}/sr_main:latest
    build:
      cache_from:
        -  ${CONTAINER_REGISTRY}/sr_main:latest
      context: .
    restart: always
    ports:
      - '3000:3000'
    environment:
      SR_INTERFACE: 0.0.0.0
