- hosts: all
  become: true
  tasks:
  - name: install useful tools
    apt: name={{item}} state=present
    with_items:
      - vim
      - tmux
      - curl
      - wget
      - git
      - fish
      - htop
      - sudo
      - make
      - python-pip
  - name: create group monofuel
    group:
      name: monofuel
      gid: 1000
      state: present
  - name: Add the user monofuel
    user:
      name: monofuel
      shell: /usr/bin/fish
      comment: The Techromancer
      uid: 1000
      groups: monofuel
      append: yes
  - name: DOCKER SUCKS
    shell: |
      # https://www.linode.com/community/questions/17114/docker-wont-start-using-the-latest-linode-kernel#answer-67343
      # why does it suck so much
      mkdir -p /etc/systemd/system/containerd.service.d/

      cat << EOF > /etc/systemd/system/containerd.service.d/override.conf
      [Service]
      ExecStartPre=

  - name: reload
    shell: systemctl daemon-reload
  - name: fetch docker installer
    get_url:
      url: https://get.docker.com
      dest: /tmp/get-docker.sh
      mode: 1770
  - name: install docker
    shell: "/tmp/get-docker.sh"
  - name: start docker
    service:
      name: docker
      enabled: yes
  - name: install docker-compose
    pip:
      name: docker-compose
  - name: add monofuel to docker group
    user:
      name: monofuel
      group: docker
      append: yes
  - name: compose build
    shell: docker-compose build
    become: yes
    become_user: monofuel
    args:
      chdir: /vagrant/
  - name: compose up
    shell: docker-compose up -d
    become: yes
    become_user: monofuel
    args:
      chdir: /vagrant/