cache:
  - file: yarn.lock
    path: node_modules
services:
  backend:
    image: registry.gitlab.com/monofuel34089/system-redemption/sr_main:builder
    port: 3000
    build:
      - yarn install --frozen-lockfile --prefer-offline
      - yarn build
    serve:
      - yarn run server
    health: /
