services:
  backend:
    image: registry.gitlab.com/monofuel34089/system-redemption/sr_main:builder
    port: 3000
    build:
      - ls -la /sr/
      # copy existing node_modules from image to current dir
      - cp -r /sr/node_modules .
      - yarn install --frozen-lockfile --prefer-offline
      - yarn prepare:client
      - yarn build:server
      - yarn build:client
    serve:
      - yarn run server
    health: /
