---
- name: copy compose
  copy:
    src: docker-compose.yml
    dest: /home/core/
- name: fetch docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.24.0-rc1/docker-compose-Linux-x86_64
    dest: /opt/bin/docker-compose
    mode: 775

- name: copy volume mount
  copy:
    src: opt-sr.mount
    dest: /etc/systemd/system
- name: start volume service
  service:
    name: opt-sr.mount
    enabled: yes
    state: started

- name: copy nginx config
  copy:
    src: sr.conf
    dest: /opt/sr/nginx/
- name: check if cert exists
  stat:
    path: /opt/sr/certbot/conf/live/sr.japura.net/privkey.pem
  register: certbot_cert

- name: stop nginx to create certs
  become: yes
  become_user: core
  shell: >
    /opt/bin/docker-compose stop nginx
  args:
    chdir: /home/core
  when: certbot_cert.stat.exists == False

- name: fetch certs
  become: yes
  become_user: core
  shell: >
    /opt/bin/docker-compose run -p 80:80 -p 443:443 --rm --entrypoint "
    certbot -t certonly -n --agree-tos --email admin@japura.net
    --renew-by-default --standalone -d sr.japura.net" certbot
  args:
    chdir: /home/core
  when: certbot_cert.stat.exists == False
- name: stop project
  become: yes
  become_user: core
  shell: /opt/bin/docker-compose down
  args:
    chdir: /home/core
- name: start project
  become: yes
  become_user: core
  shell: /opt/bin/docker-compose up -d
  args:
    chdir: /home/core
